### PR TITLE
Integrated webfonts extension.

### PR DESCRIPTION
**Pull request by thegeorgeous**
A link has been added on main page pointing towards the webfonts gallery.
The extension itself has a older frontend which I will work on if everything is okay with this.
The fonts and yaml files have been added because the extension requires it. Not sure if that is the best way.

### CODE REVIEW

**Comment by copyninja** [comment]
Is webfonts module working after this change? Can you share screenshots of webfonts page?

**Comment by thegeorgeous** [comment]
@copyninja, yes. But it is a little complicated. The build failed the first time because the webfonts module had some bugs, which I have fixed and opened a PR. I am making some more changes in the HTML of the webfonts module. I am looking into why the build failed the second time.
silpa webfonts 2015-02-04 11-02-10

**Comment by thegeorgeous** [comment]
@copyninja, build has passed. There were some bugs not related to the changes, which I have fixed.

**Comment by copyninja** [comment]
@thegeorgeous Can you also check other modules are not breaking because of this?. And some more screenshots of different sections would be great. What is api status on webfonts? 

Once I've this answer I will merge this into my PR.

**Comment by thegeorgeous** [comment]
@copyninja, except for scriptrender, the frontend for all the other modules work fine. I have opened a bug fix for scriptrender in its repo. 
Like I mentioned on the mailing list, the APIs all fail. I will start work on that.
In case of webfonts, the following urls are created
* /webfonts/list?language=Malayalam&language=Tamil
* /webfonts/text?language=Malayalam
* /webfonts?font=Meera
* webfonts/list
* webfonts/fonts/<filename>
* webfonts/gallery
In the above list everything except last two are served as JSON

**Comment by copyninja** [comment]
@thegeorgeous I was wondering if we can avoid including the fonts into repository instead use webfonts from system. This way we can avoid duplication and simply depend on system to get latest and greatest fonts.

I had started creating a tool to create required yaml file from system fonts. https://github.com/copyninja/fontinfo.git Its written in hy a lisp flavor for python. Can you think about this?

**Comment by thegeorgeous** [comment]
Yes, that would be the better way. I will look into that tool.

**Pull request closed without merging**
